<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="favicon-32x32.png" type="image/x-icon">
   <style>
    body{
           background-image: linear-gradient(to right, #FFDD68 , #F74D02 , #DD1651,#A063CA ,#B18FCB );background-attachment: fixed;
        }
   </style>
    <title>Documento apache</title>
</head>
<body>
    <h1>Minha Pagina de PHP</h1>
    <strong>
        <p><a href="index.html">retorn</a></p>
    </strong>
    <p>
        <?php
         phpinfo();
        ?>
    </p>
    
</body>
</html>