<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="favicon-32x32.png" type="image/x-icon">
    <title>Segunda página</title>
    <style>
body{
           background-image: linear-gradient(to right, #FFDD68 , #F74D02 , #DD1651,#A063CA ,#B18FCB );background-attachment: fixed;
        }

    </style>
</head>
<body>
    <h1>Aqui Você também encontra os Projetos do Bora Para Prática !!!</h1>
    <strong>
        <p>Do incrivel professor Robson Vaamonde que domina a tecnologia na parte de infraestrutura e OpenSorce !</p>
    </strong>
    <h2>
        <?php 
        echo '<h1>Teste da Linguagem HTML (HyperText Markup Language)</h1>';
        echo 'Autor: Robson Vaamonde<br>';
        echo 'Linkedin: linkedin.com/in/robson-vaamonde-0b029028/<br>';
        echo 'Site: procedimentosemti.com.br<br>';
        echo 'Facebook: facebook.com/ProcedimentosEmTI<br>';
        echo 'Facebook: facebook.com/BoraParaPratica<br>';
        echo 'Instagram: instagram.com/procedimentoem/<br>';
        echo 'YouTube: youtube.com/BoraParaPratica<br>'; 
    ?>
    </h2>
    <a href="../index.html"rel="previows">
        <strong>
            <p>retorn</p>
            <a href="../pag03.html">
                <p>next</p>
            </a>
        </strong>
    </a>
</body>
</html>